### ISSUE TITLE
Toolbar is expended not according to scroll strategy in specific scenario

### ISSUE THREAD

**Issue by eitand** [onebone/compose-collapsing-toolbar#17]
I use ScrollStrategy.ExitUntilCollapsed within my view that holds the collapseble tool bar and a list.
when i scroll all the way to the bottom and slowly scroll back up, the tool bar is expanded according to ScrollStrategy.EnterAlways

**Comment by RareScrap** [comment]
@eitand Can you please share code that reproduce problem?

**Comment by eitand** [comment]
Closing issue. Its not a bug in the library. It was an issue on an implementation i made to overcome another issue of the library ([here](https://github.com/onebone/compose-collapsing-toolbar/issues/13))
