### ISSUE TITLE
Nested scrolling support

### ISSUE THREAD

**Issue by saket** [onebone/compose-collapsing-toolbar#18]
`CollapsingToolbarScaffold` doesn't seem to report scroll events until the toolbar is fully collapsed when a nested scroll connection is provided. Is this expected? Does Compose UI require special handling from `CollapsingToolbarScaffold`?

```kotlin
CollapsingToolbarScaffold(
  modifier = Modifier.nestedScroll(nestedScrollConnection)
)
```

**Comment by saket** [comment]
I think I know why -- `CollapsingToolbarScaffold` needs to expose the nested scroll connection so that it can be used in its parent. This would be in line with what Material components is doing. Here's an example:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/samples/src/main/java/androidx/compose/material3/samples/AppBarSamples.kt;l=155;drc=e658f4148cec10e19c3c827173abebae1fb93a31

**Comment by onebone** [comment]
I'm not sure whether I understood your issue correctly, I get reported of the scroll events even if it is not fully collapsed. Can you provide the full snippet you used to reproduce the issue?

**Comment by gosr** [comment]
@saket do you have a repro project for this issue?
I have stumbled into the same issue now, but I will need some time if I need to come up with a repro project as I can't share my current code here.

Basically I'm using `CollapsingToolbarScaffold` with `ExitUntilCollapsed` scroll strategy, and as part of the content I have a composable with a multiline Text composable. This Text composable is (vertically) scrollable itself, but only becomes scrollable in the UI when the toolbar is fully collapsed.
