### ISSUE TITLE
Initial content height is incorrect

### ISSUE THREAD

**Issue by aurimas-zarskis** [onebone/compose-collapsing-toolbar#19]
Hello. 
I'm trying to make a window with button that is always at the bottom. I have column with some items and button at the end. I have added spacer between items and button to fill the remaining space making button pined to bottom. The issue is that this doesn't work with CollapsingToolbar and I have to scroll to reveal the button. I think the issue is that content height is calculated incorrectly when toolbar is initially expanded.

Here is code snippet to reproduce this issue:

```
CollapsingToolbarScaffold(
		modifier = Modifier
			.fillMaxSize(),
		state = state,
		scrollStrategy = ScrollStrategy.ExitUntilCollapsed,
		toolbar = {
			val textSize = (18 + (30 - 18) * state.toolbarState.progress).sp

			Box(
				modifier = Modifier
					.background(MaterialTheme.colors.primary)
					.fillMaxWidth()
					.height(150.dp)
					.pin()
			)

			Text(
				text = "Title",
				modifier = Modifier
					.road(Alignment.CenterStart, Alignment.BottomEnd)
					.padding(60.dp, 16.dp, 16.dp, 16.dp),
				color = Color.White,
				fontSize = textSize
			)

			Icon(
				Icons.Default.ArrowBack,
				modifier = Modifier
					.pin()
					.padding(16.dp),
				contentDescription = null
			)
		}
	) {
		Column(
			modifier = Modifier
				.fillMaxSize()
				.verticalScroll(rememberScrollState())
		) {
			Row(
				modifier = Modifier
					.fillMaxWidth()
					.padding(16.dp)
					.background(Color.DarkGray)
					.height(64.dp)
			) {}

			Row(
				modifier = Modifier
					.fillMaxWidth()
					.padding(16.dp)
					.background(Color.DarkGray)
					.height(64.dp)
			) {}

			Row(
				modifier = Modifier
					.fillMaxWidth()
					.padding(16.dp)
					.background(Color.DarkGray)
					.height(64.dp)
			) {}

			Row(
				modifier = Modifier
					.fillMaxWidth()
					.padding(16.dp)
					.background(Color.DarkGray)
					.height(64.dp)
			) {}

			Spacer(modifier = Modifier
				.fillMaxHeight()
				.weight(1f))

			Button(
				onClick = { /*TODO*/ },
				modifier = Modifier
					.padding(16.dp)
					.fillMaxWidth()
			) {
				Text(text = "Button")
			}
		}
	}

**Comment by onebone** [comment]
I have checked the behavior of CollapsingToolbarLayout from AndroidX, `android:layout_height="match_parent"` seems to work in the same way with the current behavior of the library. Can you provide me with some examples of how to solve this use case in the original CollapsingToolbarLayout?

**Comment by aurimas-zarskis** [comment]
@onebone Hey, I haven't used CollapsingToolbarLayout in old view system, so I won't be able to provide a fix for it. But I think there is still an issue of content height being calculated wrong. You could try adding 200 dp padding to bottom of button to see it. In theory it should be visible, but it pops into view only when you scroll a bit, this can also be verified using layout inspector.
If you are able to fix that issue, I think I could just add additional padding to button to get the behaviour I need.

**Comment by onebone** [comment]
Oh! You are right. I confirmed that the button is popping up, because of the wrong order of composable measurement.

By the way, I think it might be possible to give padding dynamically according to `CollapsingToolbarScaffoldState.offsetY`, though it might need some extra recomposition when scrolling appbar.

**Comment by aurimas-zarskis** [comment]
@onebone quick question. I also have a usecase when I want to force toolbar to always be collapsed. is there a way to do it?

**Comment by onebone** [comment]
@aurimas-zarskis No, it looks like there is no sound way to do that. You can create a new issue for that.

**Comment by onebone** [comment]
@aurimas-zarskis Added `enabled` parameter in the last commit!
