### ISSUE TITLE
Cannot access 'CollapsingToolbarScopeInstance': it is internal in 'me.onebone.toolbar'

### ISSUE THREAD

**Issue by Nek-12** [onebone/compose-collapsing-toolbar#22]
IntelliJ IDEA imports `me.onebone.toolbar.CollapsingToolbarScopeInstance.road` and complains that it's internal when trying to use Modifier.road() or others

IntelliJ IDEA 2021.3 RC (Ultimate Edition)
Build #IU-213.5744.125, built on November 17, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.4-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Kotlin: 213-1.5.10-release-949-IJ5744.125
Current Desktop: KDE

CollapsingToolbar v. 2.3.0

**Comment by onebone** [comment]
This library only targets Android platform for now, are you working with Android?

**Comment by Nek-12** [comment]
Yes I am. I can't import `import me.onebone.toolbar.CollapsingToolbarScope.road`

**Comment by onebone** [comment]
Not sure though, I think it is complaining because `CollapsingToolbarScope` is an interface. 

By the way, you don't have to import the `road` extension function. It automatically resolves because `CollapsingToolbarScope` is passed as a context parameter in the `toolbar` lambda.

**Comment by Nek-12** [comment]
Ah, I understand now. I'm creating my own composables for an UI Kit in the app, and this is my first time working with Compose. I have made a nooby mistake: when you move a composable to another function, you have to inherit its scope, i.e. 
```
@Composable // \/ -- scope here
fun CollapsingToolbarScope.CollapsingToolbar(
    modifier: Modifier = Modifier,
    image: Any? = null,
    title: String = stringResource(R.string.app_name),
    state: CollapsingToolbarState,
) {
```
For anyone lurking here after me - inherit the scope, and don't forget about Modifier first parameter to pass to your composable.
