### ISSUE TITLE
AbstractMethodError When Trying to Scroll

### ISSUE THREAD

**Issue by wiryadev** [onebone/compose-collapsing-toolbar#3]
**Description**
The program force closed and get AbstractMethodError when trying to scroll the screen.

**To Reproduce**
Use this code, i paste it here: [pastebin](https://pastebin.com/dg99kqB7).

**Screenshot**
![image](https://user-images.githubusercontent.com/26060382/122766633-f83eee80-d2cb-11eb-8308-cac92a8ad32f.png)
![image](https://user-images.githubusercontent.com/26060382/122766663-03921a00-d2cc-11eb-98da-560223d5ae92.png)

**Comment by onebone** [comment]
I have confirmed the issue and suspecting the difference on compose version with the library and the application using it. I will release the new version soon.

**Comment by wiryadev** [comment]
> I have confirmed the issue and suspecting the difference on compose version with the library and the application using it. I will release the new version soon.

Thanks for the reply, cant wait for that. Btw, i didnt find both CollapsingToolbarScaffold and rememberCollapsingToolbarScaffoldState when try to do something like the [example](https://github.com/onebone/compose-collapsing-toolbar/blob/master/app/src/main/java/me/onebone/toolbar/MainActivity.kt). Is it unreleased yet?

**Comment by onebone** [comment]
> > I have confirmed the issue and suspecting the difference on compose version with the library and the application using it. I will release the new version soon.
> 
> Thanks for the reply, cant wait for that. Btw, i didnt find both CollapsingToolbarScaffold and rememberCollapsingToolbarScaffoldState when try to do something like the [example](https://github.com/onebone/compose-collapsing-toolbar/blob/master/app/src/main/java/me/onebone/toolbar/MainActivity.kt). Is it unreleased yet?

Yes, CollapsingToolbarScaffold will be available on 2.1.0.

**Comment by onebone** [comment]
This issue seems to be fixed. If the error persists, feel free to reopen.

**Comment by wiryadev** [comment]
> This issue seems to be fixed. If the error persists, feel free to reopen.

I can confirm the issue have been fixed. Thanks for working on this cool library
