### ISSUE TITLE
ExitUntilCollapsed causing wierd padding on bottom

### ISSUE THREAD

**Issue by pesjak** [onebone/compose-collapsing-toolbar#30]
I have 2 composable screens with `CollapsingToolbarScaffold`. When you enter 1st screen the padding on the bottom is like it should be `0.dp`, but when you go from 1st to 2nd screen, it seems that the `ScrollStrategy.ExitUntilCollapsed` on the second screen adds some padding around `56.dp` on the bottom. If I use any other scroll strategy the problem is gone. Both screens use `ScrollStrategy.ExitUntilCollapsed`.

Update 1 (Workaround):

If you add
```
    Box(modifier = Modifier.fillMaxSize()) {
    }
```

Outside of CollapsingToolbarScaffold, the padding is now gone and it is drawn through the whole screen.

Update 2: Real solution

Don't forget to add a modifier = Modifier.fillMaxSize(), else the scaffold isn't expanded to fill the screen, even though you have enough items.

**Comment by onebone** [comment]
Are you using Compose Navigation for the screen navigation?

**Comment by onebone** [comment]
Thank you for clarifying, I'll close the issue! 😃
