### ISSUE TITLE
Cannot round Nan value

### ISSUE THREAD

**Issue by subashz** [onebone/compose-collapsing-toolbar#4]
Full Log here: https://pastebin.com/wfmWV4bq
Impl Code:
  

    val headerBg =
        "https://static.vecteezy.com/system/resources/previews/001/887/504/non_2x/light-blue-gradient-blur-layout-vector.jpg"

    val state = rememberCollapsingToolbarScaffoldState()
    CollapsingToolbarScaffold(
        modifier = Modifier.fillMaxWidth(),
        state = state,
        toolbar = {

            Box(
                modifier = Modifier.parallax(0.5f)
            ) {
                Image(
                    painter = rememberCoilPainter(
                        request = headerBg,
                        fadeIn = true,
                    ),
                    contentDescription = "",
                    contentScale = ContentScale.Crop,
                    modifier = Modifier.height(300.dp)
                )

                HomeHeader()
            }
        },

        scrollStrategy = ScrollStrategy.ExitUntilCollapsed
    ) {
        LazyColumn(modifier = Modifier.fillMaxWidth()) {

            item {
                Text(
                    text = "Test",
                    style = TextStyle(
                        color = androidx.compose.ui.graphics.Color.Black,
                        fontSize = 14.sp,
                        letterSpacing = (0.2f).sp
                    )
                )
            }

            itemsIndexed(tripList) { pos, data ->
                HomeTripItem(homeTripModel = data)

                Spacer(modifier = Modifier.height(24.dp))

            }

        }
    }

**Comment by onebone** [comment]
I have confirmed the issue and will push the workaround for it. By the way, `HomeHeader()` is at the same level as the `Image()`, may I ask the objective for that?

**Comment by Shusshu** [comment]
release it?
