### ISSUE TITLE
Expand when needed

### ISSUE THREAD

**Issue by alashow** [onebone/compose-collapsing-toolbar#5]
Hello. This works great for collapsing toolbars, but is there a way to expand/collapse the toolbar when needed?

My use case is that I have a search input on the toolbar and I want to expand the toolbar when keyboard is visible (via [`LocalWindowInsets.current.ime.isVisible`](https://google.github.io/accompanist/insets/))

**Comment by onebone** [comment]
This feature has just released as experimental in 2.2.0 with `CollapsingToolbarState.expand()` :+1:

**Comment by onebone** [comment]
@Shusshu May I ask you to create a new issue with some extra information so that I could reproduce it?

**Comment by alashow** [comment]
https://issuetracker.google.com/issues/197553056 could be related

**Comment by onebone** [comment]
> https://issuetracker.google.com/issues/197553056 could be related

Thank you for sharing 😃 Since I have experienced some trouble regarding that issue when I was testing fling behaviors, it is happy to hear that it has fixed. But how can it be related to the manual collapsing/expansion using animators?

**Comment by alashow** [comment]
I accidentally thought this thread was about flings again, nvm 😬
