### ISSUE TITLE
CollapsingToolbar does not consume fling

### ISSUE THREAD

**Issue by onebone** [onebone/compose-collapsing-toolbar#7]
# Summary
Although the user flings the content all the way to the top and there is a left velocity that CollapsingToolbar can consume, it does not consume fling.

# Partial Solution
I can implement fling behavior by overriding `onPreScroll()` and `onPostScroll()` callbacks in NestedScrollConnection. However, the problem is that as of Jetpack Compose 1.0.0-rc01 it calculates fling velocity by relative position of the content (For the actual source code calculating the velocity, refer to [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Draggable.kt;l=326-340;drc=c235569e0f8dee12ab42657d262b1988fddb443b) and [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerEvent.kt;l=164-165;drc=7284ee4acc4c6687938399f9cd10dca628b11f48)). As an offset of content moves as the toolbar is expanded/collapsed, the velocity that is calculated inside a child(moving) layout does not provide a valid velocity as a whole resulting in buggy fling behavior because the change in relative position hardly matches the global position change in screen surface.

# Further Observations
Jetpack Compose basically utilizes event bubble(where event is passed from child through its parents) while we can capture an event before the child processes it using [Initial PointerEventPass](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerEvent.kt;l=266-268;drc=7284ee4acc4c6687938399f9cd10dca628b11f48). However using `PointerEventPass.Initial` type will pay high implementation cost as there is an only small set of high level API with Initial passing type.

# Traditional Android UI System
The traditional Android UI components which support nested scrolling such as RecyclerView and NestedScrollView calculate velocity using relative position, but they adjust their offset when its relative position to the screen has changed as we can see at [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:recyclerview/recyclerview/src/main/java/androidx/recyclerview/widget/RecyclerView.java;l=3444-3445,3522-3523;drc=dbdba1b15d56a8d30b63785d3758897de15b1018) and [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/widget/NestedScrollView.java;l=838,921;drc=a49a43ca43219db45652c5cf5812e4454b15e731).

# Conclusion
At the moment, I could not find a method to implement flinging behavior correctly, I will leave this as an issue until a valid way is found.

**Comment by onebone** [comment]
## Progress
I found that the the value in the `DragDelta` which is used to provide scroll delta for `onNestedPreScroll()` and `onNestedScroll()` is calculated using absolute position in screen (refer [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerInputEventProcessor.kt;l=137-138,148)). A possible solution from this fact is to calculate velocity on the parent using these scroll delta values and then override the velocity at `onNestedPreScroll()`. `onNestedPreScroll()` does not check if the available scroll delta changes its sign, so we can override it.

**Comment by alashow** [comment]
This might be related https://issuetracker.google.com/issues/179417109

**Comment by onebone** [comment]
> This might be related https://issuetracker.google.com/issues/179417109

Thank you for pointing the issue. It is sad that the commit has reverted since I thought calculation based on a relative position was correct.

**Comment by onebone** [comment]
Fixed as of 2.2.0.
