### ISSUE TITLE
Used without consent

### ISSUE THREAD

**Issue by ghost** [onebone/compose-collapsing-toolbar#86]
Um, I don't know what this is.  Standard on ALL phones?

**Comment by JayP198636** [comment]
Ummm... Is that a joke of some sort? Standard Trying To Get Past The Data Protection Officer, Make A Phone Server LogIn Device, Steal Information, Credit/Debit Card, Routing&Account Numbers, And Blackmail Central

**Comment by ghost** [comment]
JayP, I have no damn clue what you are talking about.  I just found this account. I did not even know about it.  I was blackmailed. Well, held hostage for ransom. I paid that my damn self.  I do not steal nor blackmail.  Still getting videos on TikTok?  I sent you one you never opened.
